### PR TITLE
The cookbook should pass Rubocop lint testing.

### PR DESCRIPTION
**Pull request by nathenharvey**

### CODE REVIEW

**Comment by mwrock** [comment]
I can see some complaining but I think this increases quality and readability. :+1:

**Comment by nathwill** [comment]
:birthday: this is terrific. i assume projects will still be able to use a `.rubocop.yml` to fine-tune their personal preference (?), so i don't see this being too oppressive, though it will at least enforce internal consistency, which should really help projects with multiple committers.

**Comment by tas50** [comment]
@nathwill Rubocop would use any rubocop.yml rule and would also respect the inline rule disabling comments so you could tune which rules you found important.

**Comment by nathwill** [comment]
@tas50 thought so, thanks for confirming!

**Comment by nathenharvey** [comment]
also, important to highlight that this metric only cares about the `--lint` rules in rubocop.  Not _all_ the rules.

**Comment by johnbellone** [comment]
If it helps we've been using a [rubocop.yml file](https://github.com/bloomberg/zookeeper-cookbook/blob/master/.rubocop.yml) in our canned cookbook generator.

**Comment by tas50** [comment]
:+1:

**Pull request merged**
