### PR TITLE
Update the Apache-2.0 license string

### PR DESCRIPTION
**Pull request by tas50**
The standard has the - in it

### CODE REVIEW

**Comment by robbkidd** [comment]
Per the [SPDX standard formats](https://spdx.org/licenses/), I agree.

**Comment by shortdudey123** [comment]
If you are going by that list, probably need to update the `GNU` one's as well

**Comment by tas50** [comment]
@shortdudey123 We just discussed the need to update all of these actually

**Comment by shortdudey123** [comment]
Ah, sounds good :)

**Pull request closed without merging**
