### PR TITLE
Remove points until we can see the big picture

### PR DESCRIPTION
**Pull request by tas50**
Most conversations right now are revolving around the point values for
each check. These aren't very productive conversations right now since
we can't see the big picture to know what the total point count is.  I
propose we shelf the points concept until we have a clear picture of
what the MVP quality metrics are.  From there we can determine an
initial total and what share of that total each metric should comprise.

### CODE REVIEW

**Comment by mattray** [comment]
I agree with this completely. I think having Yes/No for an indicator allows one to quickly see that a cookbook has "10 out of 12" quality indicators achieved. Even if some of the metrics are easier than others, you can tell the difference between "4 of 12" vs. "12 of 12" for example.

**Comment by mwrock** [comment]
I think this is a really good idea and it removes the confusion of how one rule weighs against another. I do think that in the end a numeric scale can be extremely helpful and influential. If done wrong it can be very destructive. This is a good approach to safely test the quality metric.

**Comment by tas50** [comment]
Just to clarify I don't think we should eliminate the point system all together.  I just think during the initial conversation of what metrics we want we're not helping ourselves by debating the difference between 5 points and 10 points.

**Comment by martinb3** [comment]
:+1: it feels too early for points.

**Comment by thommay** [comment]
:+1: :100:

**Comment by usepowershell** [comment]
:+1:

**Comment by iennae** [comment]
:+1:

**Pull request merged**
