### PR TITLE
The cookbook has an `issues_url` in its metadata.

### PR DESCRIPTION
**Pull request by johnbellone**

### CODE REVIEW

**Comment by nathenharvey** [comment]
:+1:

**Comment by tas50** [comment]
I'd like the + to be higher here, but this is a huge one to check for :+1:

**Comment by nathenharvey** [comment]
@tas50 @johnbellone how much higher to you think the + should be?  maybe 5 points?

**Comment by johnbellone** [comment]
Five points is better than one, but what's the yard stick that we should be using?

**Comment by tas50** [comment]
:+1: We can worry about the point scale later.

**Pull request merged**
