### PR TITLE
Cookbook supports multiple platforms

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by nathwill** [comment]
:+1: it'd be cool if this was tied to the tier1 platforms supported by chef core too.

edit: fixed thumb direction, silly autocomplete

**Comment by tas50** [comment]
Ideally cookbook writers would support something like Ubuntu/RHEL, but I suspect you'll probably see something like Ubuntu/Debian or RHEL/CentOS.  It's still a win to get additional metadata.  If we move back to the points system it would be nice to assign points per additional platform.

**Comment by nathenharvey** [comment]
:+1:

**Comment by pburkholder** [comment]
Shouldn't test-kitchen pass tests which use multiple platforms?

**Pull request merged**
