### PR TITLE
The cookbook has 'supports' specified in its metadata.

### PR DESCRIPTION
**Pull request by johnbellone**
A cookbook consumer should be confident that a cookbook was written with
their target platform in mind.

### CODE REVIEW

**Comment by tas50** [comment]
I'd like the + to be higher here, but this is a huge one to check for :+1:

**Comment by nathenharvey** [comment]
:+1:

**Comment by nathenharvey** [comment]
5 points?  10?

**Comment by tas50** [comment]
:+1: But this is a really important thing to include in metadata and 10 points would be nice.  This is more important than the lint rule which was 10

**Pull request merged**
